/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main_Form;

import java.awt.CardLayout;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;



/**
 *
 * @author HP
 */
public class FormPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form Form
     */
    JPanel bottomPanel;
    public FormPanel(JPanel bottomPanel) {
        this.bottomPanel=bottomPanel;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderbuttonGroup1 = new javax.swing.ButtonGroup();
        titlejLabel1 = new javax.swing.JLabel();
        namejLabel1 = new javax.swing.JLabel();
        namejTextField1 = new javax.swing.JTextField();
        agejLabel1 = new javax.swing.JLabel();
        agejTextField1 = new javax.swing.JTextField();
        submitjButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setPreferredSize(new java.awt.Dimension(400, 400));

        titlejLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        titlejLabel1.setText("User Details");

        namejLabel1.setText("Name");

        agejLabel1.setText("Age");

        submitjButton1.setText("Submit");
        submitjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agejLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namejLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(agejTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(namejTextField1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addComponent(submitjButton1)
                .addContainerGap(183, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titlejLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(titlejLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namejTextField1)
                    .addComponent(namejLabel1))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agejTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(agejLabel1))
                .addGap(68, 68, 68)
                .addComponent(submitjButton1)
                .addContainerGap(161, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
  private boolean validateInputs() {
    // Validation for First Name
    if (namejTextField1.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter the First Name.", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    // Validation for Age (should be an integer value)
    try {
        int age = Integer.parseInt(agejTextField1.getText());
        if (age < 0 || agejTextField1.getText().length()>2) {
            throw new NumberFormatException();
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter a valid integer for Age.", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    return true;
  }
    
    private void submitjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitjButton1ActionPerformed
        // TODO add your handling code here:
        // Validate inputs before proceeding
        if (validateInputs()) {
    User newUser = new User();
 try{
     newUser.setName(namejTextField1.getText());  
     newUser.setAge(Integer.parseInt(agejTextField1.getText()));
     DatabaseConnector.addUser(newUser);
JOptionPane.showMessageDialog(null, "User registered Successfully");
     
cleanUp();
 }catch(Exception e){
  JOptionPane.showMessageDialog(this, e.getMessage());
 }
    }//GEN-LAST:event_submitjButton1ActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GenderbuttonGroup1;
    private javax.swing.JLabel agejLabel1;
    private javax.swing.JTextField agejTextField1;
    private javax.swing.JLabel namejLabel1;
    private javax.swing.JTextField namejTextField1;
    private javax.swing.JButton submitjButton1;
    private javax.swing.JLabel titlejLabel1;
    // End of variables declaration//GEN-END:variables
public void cleanUp(){
    namejTextField1.setText("");
    agejTextField1.setText("");
}
}
